name = "iaenblanco-nextjs"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[vars]
NODE_ENV = "production"

[build]
command = "npm run build"
cwd = "."

[build.environment_variables]
NODE_ENV = "production"
