name = "iaenblanco-nextjs"
compatibility_date = "2024-01-01"

[env.production]
name = "iaenblanco-nextjs"

# Configuraci√≥n para Cloudflare Pages
[[pages_builds]]
build_command = "npm run build"
build_output_directory = "out"
